# Test deploy: gcloud app deploy --version test --no-promote
# Prod deploy: gcloud app deploy --version www

runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /$
  script: index.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /asset
  static_dir: asset 
- url: /images
  static_dir: images 
- url: /js
  static_dir: js 
- url: /app
  static_dir: app 
- url: /css
  static_dir: css 
