runtime: php55
api_version: 1

# TODO(shai): seperate upload and this to different services.
# the following line is copied from yapi/upload/app.yaml so they won't override each other.
instance_class: F4_1G

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  secure: always

- url: /$
  script: index.php
  secure: always

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  secure: always

- url: /asset
  static_dir: asset
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /app
  static_dir: app
  secure: always

- url: /css
  static_dir: css
  secure: always
